name: policy-build-release

on:
  workflow_dispatch:
  push:
    tags:
    - '*'

jobs:
  release_policy:
    runs-on: ubuntu-latest
    name: build
    steps:
    
    - uses: actions/checkout@v2
    
    - uses: aserto-dev/sver-action@v0.0.14
      name: Calculate Tag
      id: "sver"
      with:
        next: patch

    - name: Policy Login
      id: policy-login
      uses: opcr-io/policy-login-action@v1
      env:
        OPCR_BOT_PAT: ${{ secrets.OPCR_BOT_PAT }}
      with:
        username: opcr-bot
        password: ${{ env.OPCR_BOT_PAT }}

    - name: Policy Build
      id: policy-build
      uses: opcr-io/policy-build-action@v1
      with:
        src: src
        tag: build-image:${{ steps.sver.outputs.version }}
        revision: "$GITHUB_SHA"

    - name: Policy Tag
      id: policy-tag
      uses: opcr-io/policy-tag-action@v1
      with:
        source_tag: build-image:${{ steps.sver.outputs.version }}
        target_tag: policy-test/policy-test:${{ steps.sver.outputs.version }}

    - name: Policy Push
      id: policy-push
      uses: opcr-io/policy-push-action@v1
      with:
        tag: policy-test/policy-test:${{ steps.sver.outputs.version }}

    - name: Policy Remove
      id: policy-rm
      uses: opcr-io/policy-rm-action@v1
      with:
        tag: policy-test/policy-test:${{ steps.sver.outputs.version }}

    - name: Policy Pull
      id: policy-pull
      uses: opcr-io/policy-pull-action@v1
      with:
        tag: policy-test/policy-test:${{ steps.sver.outputs.version }}

    - name: Policy Save
      id: policy-save
      uses: opcr-io/policy-save-action@v1
      with:
        tag: policy-test/policy-test:${{ steps.sver.outputs.version }}
        file: /bundle.tar.gz

    - name: Dump bundle
      run: |
        tar -tvf /bundle.tar.gz

    - name: Policy Logout
      id: policy-logout
      uses: opcr-io/policy-logout-action@v1
