name: policy-build-release

on:
  workflow_dispatch:
  push:
    tags:
    - '*'

jobs:
  release_policy:
    runs-on: ubuntu-latest
    name: build
    steps:
    
    - uses: actions/checkout@v2
    
    - uses: aserto-dev/sver-action@v0.0.13
      name: Calculate Tag
      id: "sver"
      with:
        next: patch

    - name: Policy Login
      id: policy-login
      uses: opcr-io/policy-login-action@v1.0.1
      env:
        OPCR_BOT_PAT: ${{ secrets.OPCR_BOT_PAT }}
      with:
        username: opcr-bot
        password: ${{ env.OPCR_BOT_PAT }}

    - name: Policy Build
      id: policy-build
      uses: opcr-io/policy-build-action@v1.0.1
      with:
        src: src
        tag: policy-test/policy-test:${{ steps.sver.outputs.version }}
        revision: "$GITHUB_SHA"

    - name: Policy Push
      id: policy-push
      uses: opcr-io/policy-push-action@v1.0.1
      with:
        tag: policy-test/policy-test:${{ steps.sver.outputs.version }}

    - name: Policy Logout
      id: policy-logout
      uses: opcr-io/policy-logout-action@v1.0.1
