name: policy-build-release

on:
  workflow_dispatch:
  push:
    tags:
    - '*'

jobs:
  release_policy:
    runs-on: ubuntu-latest
    name: build
    steps:
    
    - uses: actions/checkout@v2
    
    - uses: aserto-dev/sver@v0.0.14
      name: Calculate Tag
      id: "sver"
      with:
        next: patch

    - name: Policy Login
      id: policy-login
      uses: opcr-io/policy-login-action@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        username: policy-bot
        password: "$GITHUB_TOKEN"

    - name: Policy Build
      id: policy-build
      uses: opcr-io/policy-build-action@v1
      with:
        src: peoplefinder/src
        tag: datadude/peoplefinder:${{ steps.sver.outputs.version }}
        revision: "$GITHUB_SHA"

    - name: Policy Push
      id: policy-push
      uses: opcr-io/policy-push-action@v1
      with:
        tag: datadude/peoplefinder:${{ steps.sver.outputs.version }}

    - name: Policy Logout
      id: policy-logout
      uses: opcr-io/policy-logout-action@v1
